### DISCUSSION TITLE
MQTT - HA integration example(s)

### DISCUSSION THREAD

**Discussion by aly-fly** [Edzelf/ESP32Radio-V2#165] [Show and tell]
I spent handful of hours getting radio integrated into Home Assistant. Documentation is non-existent. That's why I decided to share a working example of the code.
1. Set up MQTT broker (if not already), like Mosquitto.
2. Link broker to HA - set up generic [MQTT integration](https://www.home-assistant.io/integrations/mqtt/).
3. Configure Radio's MQTT config with IP / address, port, username and password of the Broker.
4. Set `mqttprefix` to a useful unique ID, like "RadioLivingRoom" or similar.
5. Restart radio.
6. Use MQTT analyzer like MQTT-Explorer, connect to your Broker and look for the messages from the radio.
7. Open the main HA config file `configuration.yaml` in your favorite text editor.
8. Add following code at the end, similar to this and modify to suit your parameters and config.
9. Open HA developer Tools, check config, restart HA. On further modifications you can use `Reload manually configured MQTT` command.
10. Open Entities of the MQTT integration and set Location for each one as per your needs.

```

mqtt:
# MQTT Radio
# https://www.home-assistant.io/integrations/number.mqtt/
  - number:
      name: "Radio Xmas Volume"
      unique_id: "RadioXmasVolume"
      state_topic : "radioxmas/volume"
      command_topic: "radioxmas/command"
      command_template: "volume={{ value }}"
      min: 0
      max: 100
      step: 5
      icon: mdi:volume-high
      mode: slider

  - number:
      name: "Radio Xmas Preset"
      unique_id: "RadioXmasPreset"
      state_topic : "radioxmas/preset"
      command_topic: "radioxmas/command"
      command_template: "preset={{ value }}"
      min: 0
      max: 4
      step: 1
      icon: mdi:knob
      mode: box

# https://www.home-assistant.io/integrations/text.mqtt/
  - text:
      name: "Radio Xmas Station"
      unique_id: "RadioXmasStationName"
      icon: mdi:antenna
      state_topic: "radioxmas/icy/name"
      command_topic: "radioxmas/none"

  - text:
      name: "Radio Xmas Title"
      unique_id: "RadioXmasSongTitle"
      icon: mdi:script-text-outline
      state_topic: "radioxmas/icy/streamtitle"
      command_topic: "radioxmas/none"

```

End result:

![image](https://github.com/user-attachments/assets/4ff0b6ea-85d8-4541-9c2d-3f0a73f3c74d)
